### PR TITLE
♻️ Reflect template and event changes without restarting app

### LINKED ISSUE #193: Expired token datasource failure
The API provider fails to handle the expired token message returned from API. API Wrapper handles this, Web however doesn't use API Wrapper for the communication with API.

```
10:19:08.738Z  INFO dadi-web: GET datasource "articles": http://127.0.0.1:8011/1.0/radio/articles?count=5&page=1&filter={}&fields={}&sort={} (module=remote)

[2017-07-28 11:19:08.956] [LOG]   { 'www-authenticate': 'Bearer, error="invalid_token", error_description="Invalid or expired access token"',
  'content-type': 'application/json',
  'content-length': '18',
  date: 'Fri, 28 Jul 2017 10:19:08 GMT',
  connection: 'keep-alive' }

10:19:08.957Z ERROR dadi-web: Unauthorized (401): http://127.0.0.1:8011/1.0/radio/articles?count=5&page=1&filter={}&fields={}&sort={} (module=dadi-api)

[2017-07-28 11:19:08.958] [LOG]   { Error: Datasource "articles" failed. Unauthorized (401): http://127.0.0.1:8011/1.0/radio/articles?count=5&page=1&filter={}&fields={}&sort={}
{"statusCode":401}
message: 'Datasource "articles" failed. Unauthorized (401): http://127.0.0.1:8011/1.0/radio/articles?count=5&page=1&filter={}&fields={}&sort={}\n{"statusCode":401}',
  remoteIp: '127.0.0.1',
  remotePort: 8011 }
```

### PR DESCRIPTION
**Pull request by abovebored**
Allows changes to events & template partials/includes to reinitialise the template engine without restarting the app.

Closes #193

### CODE REVIEW

File: dadi/lib/index.js [hunk 1]
```diff
@@ -510,12 +511,20 @@ Server.prototype.loadApi = function (options, reload, callback) {
...
+
+      // Reload
       this.updatePages(options.pagePath, options, true)
     })
 
     this.addMonitor(options.pagePath, pageFile => {
       this.updatePages(options.pagePath, options, true)
       this.compile(options)
+
+      templateStore.reInitilise()
```
Comment (eduardoboucas) [inline dadi/lib/index.js]: Typo?
