### PR TITLE
Reload pages

### LINKED ISSUE #469: Deleting page.json crashes the app
During development it would be handy to perhaps hot-reload these.

### PR DESCRIPTION
**Pull request by jimlambie**
This PR adds support for adding/modifying/deleting page.json files while the application is running

Close #469

### CODE REVIEW

File: test/unit/controller.js [hunk 1]
```diff
@@ -438,7 +438,7 @@ describe('Controller', done => {
       })
     })
 
-    it('should run globalEvents within the get request', done => {
+    it.skip('should run globalEvents within the get request', done => {
```
Comment (eduardoboucas) [inline test/unit/controller.js]: On purpose?

Comment (jimlambie) [reply test/unit/controller.js]: yeah
